name: madurai_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  translator: ^1.0.3+1
  provider: ^6.0.5
  http: ^1.1.0
  intl: ^0.18.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4+2
  geolocator: ^10.1.0
  permission_handler: ^10.4.3
  flutter_blue_plus: ^1.32.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
